### ISSUE TITLE
Can't get it to work on 4.19

### ISSUE THREAD

**Issue by varomix** [proletariatgames/unreal.hx#83]
Please HELP!
Hi, I'm using the development branch but I can't make it work
whatever I do I get this error, I tried the dev_4.19 branch, same thing
I'm following the instructions on the README then I open the project and hit compile and I get this error

```
CompilerResultsLog: ERROR: /media/LNX_PROJ_2017/UE4_PROJx_2018/haxeTest01/Plugins/UnrealHX/Source/HaxeInit/BuildApi.Build.cs(359,53) : error CS0117: `UnrealBuildTool.UProjectInfo' does not contain a definition for `FilterGameProjects'
CompilerResultsLog: ERROR: /media/LNX_PROJ_2017/UE4_PROJx_2018/haxeTest01/Plugins/UnrealHX/Source/HaxeInit/BuildApi.Build.cs(362,35) : error CS0117: `UnrealBuildTool.UProjectInfo' does not contain a definition for `FilterGameProjects'
CompilerResultsLog: ERROR: Unable to compile source files.
```

Thanks

**Comment by sebastienduval** [comment]
Same here.

**Comment by datee** [comment]
Yep it wont build right now but a fix is coming soon i belive.

**Comment by waneck** [comment]
Yes we're working on this, a fix should be available this week still. Sorry about that! For now it's best to keep on the 4.17 version. See https://github.com/proletariatgames/unreal.hx/releases

**Comment by varomix** [comment]
I rather wait for the fix :)

**Comment by waneck** [comment]
This should be fixed now. Let me know if you find any other issues! Thanks

**Comment by varomix** [comment]
Hi
well, is working a little bit more but still getting a compile issue

```Compiling group: cppia
g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DSTATIC_LINK(static) -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_SCRIPTABLE(haxe) -DHXCPP_API_LEVEL=332(haxe) -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include ... tags=[haxe]
 - src/hx/cppia/CppiaCtx.cpp 
 - src/hx/cppia/CppiaFunction.cpp 
 - src/hx/cppia/CppiaClasses.cpp 
 - src/hx/cppia/ArrayVirtual.cpp 
 - src/hx/cppia/CppiaModule.cpp 
 - src/hx/cppia/ArrayBuiltin.cpp 
 - src/hx/cppia/StringBuiltin.cpp 
 - src/hx/cppia/CppiaCompiler.cpp 
 - src/hx/cppia/HaxeNative.cpp 
 - src/hx/cppia/Cppia.cpp 
 - src/hx/cppia/CppiaVars.cpp 
 - src/hx/cppia/GlobalBuiltin.cpp 
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: g++: error: : No such file or directory
ERROR: Error: Build failed
Error :  -> returned with exit code 1
Error : Build failed: Haxe compilation failed
ERROR: Error :  -> returned with exit code 1
ERROR: Error : Build failed: Build failed
ERROR: Error: Haxe compilation failed
ERROR: Unable to instantiate module 'haxetest': System.Exception: Haxe compilation failed
         at HaxeModuleRules.callHaxe (UnrealBuildTool.ModuleRules rules, HaxeCompilationInfo info, HaxeConfigOptions options) [0x00228] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at HaxeModuleRules.setupHaxeTarget (UnrealBuildTool.ModuleRules rules, System.Boolean forceHaxeCompilation, HaxeConfigOptions options) [0x0033c] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at HaxeModuleRules.run () [0x000ee] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at BaseModuleRules..ctor (UnrealBuildTool.ReadOnlyTargetRules target) [0x00017] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at HaxeModuleRules..ctor (UnrealBuildTool.ReadOnlyTargetRules target) [0x00012] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at haxetest..ctor (UnrealBuildTool.ReadOnlyTargetRules Target) [0x00000] in <136b667a3a7c46679c4e6b229d71249a>:0 
         at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
         at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0 
       (referenced via haxetest.Target.cs)
```

I complaining about **haxetest** is that something instalable via haxelib cause I can't find it with that name

thanks

**Comment by varomix** [comment]
Sorry haxetest is the name of my project, that is not the issue :)

**Comment by waneck** [comment]
Hi there! Could you try running the build with the HXCPP_VERBOSE=1
environment variable and show the full resulting log?

Thanks!
Caue

2018-04-04 23:52 GMT-03:00 varomix <notifications@github.com>:

**Comment by varomix** [comment]
This is what  I get 
```
- Running command: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaCompiler.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaCompiler.o


ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/Cppia.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_Cppia.o
ERROR: 
ERROR: g++: error: : No such file or directory
ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaClasses.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaClasses.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaFunction.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaFunction.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaCtx.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaCtx.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaVars.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaVars.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/ArrayVirtual.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_ArrayVirtual.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/GlobalBuiltin.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_GlobalBuiltin.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/HaxeNative.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_HaxeNative.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/CppiaModule.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_CppiaModule.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/ArrayBuiltin.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_ArrayBuiltin.o
ERROR: 
ERROR: g++: error: : No such file or directory

ERROR: Error: Error while running command
ERROR: g++ -DHX_UNDEFINE_H -DCPPIA_JIT  -I/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Template/Shared -c -fvisibility=hidden -g -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=332 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,4,188/include -x c++ -frtti -Wno-invalid-offsetof /usr/lib/haxe/lib/hxcpp/3,4,188/src/hx/cppia/StringBuiltin.cpp -o/media/LNX_PROJ_2017/UE4_PROJx_2018/haxetest/Intermediate/Haxe/haxetest-Linux-Development-Editor/Static/obj/linux64-stat-debug/2b50853f_StringBuiltin.o
ERROR: 
ERROR: g++: error: : No such file or directory
ERROR: Error: Build failed
Error :  -> returned with exit code 1
Error : Build failed: Haxe compilation failed
ERROR: Error :  -> returned with exit code 1
ERROR: Error : Build failed: Build failed
ERROR: Error: Haxe compilation failed
```

**Comment by varomix** [comment]
ok that was weird, cause I run those g++ command on terminal and they do compile and now the project build, weird
now let's try to use this

thank you

**Comment by waneck** [comment]
That's weird indeed. How were you compiling before? Through the terminal as
well? If it was through some other ui, it could be a PATH issue. Also, now
that I think about it, it might be worth setting CXX=clang++ when compiling
because that's what Unreal uses. It's been some time since I compiled
Unreal.hx on an actual Linux box (unfortunately) - we've been only doing it
through the cross compiler on windows - so let me know how it goes!

**Comment by varomix** [comment]
I was compiling by just opening the project on terminal and it starts the compilation
but now it doesn't want to compile a haxe script 

![image](https://user-images.githubusercontent.com/728059/38384514-9b8270c8-38cc-11e8-9ef6-bea4e4aeca18.png)

I have the file in Haxe/Scripts and I'm running `haxe gen-build-script.hxml`

**Comment by waneck** [comment]
You need to put this file in the Haxe/Scripts/haxetest directory, since
it's got the haxetest package

**Comment by varomix** [comment]
oh damn, pff hehe, my mistake
great it works now man, cppia compiles super quick, now let's try to build something with this
thank you very much for the help

Also, now you can say it runs on Linux as well :)

Question
When shipping a game, there won't be any external dependencies right, cause at the end of the day it all compiles to C++, so won't be any issues to export to any platform, am I right?

thanks again

**Comment by waneck** [comment]
Awesome :)
Right - all dependencies are statically linked, and as an extra benefit, cppia classes compile as actual C++ code when packaging, so they'll have a good speed increase as well
