### ISSUE TITLE
HaxeCompiler error in editor, ue4.14

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#65]
Greetings,
I am attempting to get unreal.hx working with ue4.14, and I have gotten as far as running init-plugin.hxml successfully, but now when I try to compile, I get the following error:

`CompilerResultsLog:Error: Error HaxeCompiler: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp(116) : error C2819: type 'uhx::glues::TArrayImpl_Glue_obj' does not have an overloaded member 'operator ->'
CompilerResultsLog:Error: Error HaxeCompiler: C:/Users/Jamie/Dropbox/RooVR/Source/RooVR/../RooVR/Generated/Public/uhx/glues/TArrayImpl_Glue.h(26) : note: see declaration of 'uhx::glues::TArrayImpl_Glue_obj'
CompilerResultsLog:Error: Error HaxeCompiler: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp(116) : note: did you intend to use '.' instead?
CompilerResultsLog:Error: Error HaxeCompiler: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp(116) : error C2232: '->uhx::glues::TArrayImpl_Glue_obj::set_Item': left operand has 'class' type, use '.'`

Has anyone else encountered this before?

**Comment by jrgalim** [comment]
moving on to ue4.14

**Comment by waneck** [comment]
Hey, sorry I missed your bug report. Hopefully you've got it working with the 4.14 branch. The 4.16 branch is also experimentally supporting 4.14 as well. It's still a little bit unstable though, as we've changed quite a lot, and are fleshing out the bugs for a release

**Comment by jrgalim** [comment]
Not a problem, I'm moving on with 4.16, but ran into some trouble with that branch as well (was about to post about it).  If you're working towards a release, though, that is very exciting and I will hold off until that is available.  Thank you for your continued work on this plugin, after coming from UDK/unrealscript, I've been craving the chance to dive in with Haxe!

**Comment by waneck** [comment]
Please report if you find any 4.16 bugs :) Thank you!
