### ISSUE TITLE
Cannot compile in 4.10

### ISSUE THREAD

**Issue by krupin-maxim** [proletariatgames/unreal.hx#31]
Haxe classes were compiled with success in Unreal 4.9, but when upgraded to 4.10 I've got the error: "ERROR: UBT ERROR: Failed to produce item: /home/maxim/Documents/Unreal Projects/MyProject6/Binaries/Linux/libUE4Editor-MyProject6-8385.so".

**Comment by waneck** [comment]
Do you have more information? That's probably because we're using the 4.9
classes definitions on 4.10 - you'll need to run the generator for it
yourself.

**Comment by krupin-maxim** [comment]
I am sorry, what command is for running the generator?

**Comment by waneck** [comment]
There are some steps on https://github.com/proletariatgames/UE4HaxeExternGenerator - but you'll need an empty project to get it to work.
Can you attach the whole compilation log so we can try to figure out what is failing on 4.10 ?

**Comment by krupin-maxim** [comment]
Hello, I did this steps for UE4HaxeExternGenerator. But compile errors still exist. I attached log:

[unreal_log.txt](https://github.com/proletariatgames/unreal.hx/files/86783/unreal_log.txt)


I see error:
`/home/maxim/Documents/Unreal Projects/MyProject8/Source/MyProject8/Generated/Private/__pvt/_hx_unreal/ULevel_Glue.cpp:100:182: error: no member named 'ActiveRuntimeMovieScenePlayers' in '_staticcall_get_ActiveRuntimeMovieScenePlayers'
                                return new __pvt::_hx_unreal::TArrayImpl_Glue_UE_obj<UObject *>(PExternal<TArray<UObject *>>::wrap( &(( (ULevel *) _s_self )->*(&_staticcall_get_ActiveRuntimeMovieScenePlayers::ActiveRuntimeMovieScenePlayers)) ));
                                                                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/maxim/Documents/Unreal Projects/MyProject8/Source/MyProject8/Generated/Private/__pvt/_hx_unreal/ULevel_Glue.cpp:117:81: error: no member named 'ActiveRuntimeMovieScenePlayers' in '_staticcall_set_ActiveRuntimeMovieScenePlayers'
                                (( (ULevel *) _s_self )->*(&_staticcall_set_ActiveRuntimeMovieScenePlayers::ActiveRuntimeMovieScenePlayers)) = (*(( (TArray<UObject *> *) (::unreal::helpers::UEPointer::getPointer(_s_value)) )));
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/maxim/Documents/Unreal Projects/MyProject8/Source/MyProject8/Generated/Private/__pvt/_hx_unreal/ULevel_Glue.cpp:134:175: error: no member named 'MovieSceneBindingsArray' in '_staticcall_get_MovieSceneBindingsArray'
                                return new __pvt::_hx_unreal::TArrayImpl_Glue_UE_obj<UObject *>(PExternal<TArray<UObject *>>::wrap( &(( (ULevel *) _s_self )->*(&_staticcall_get_MovieSceneBindingsArray::MovieSceneBindingsArray)) ));
                                                                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/maxim/Documents/Unreal Projects/MyProject8/Source/MyProject8/Generated/Private/__pvt/_hx_unreal/ULevel_Glue.cpp:151:74: error: no member named 'MovieSceneBindingsArray' in '_staticcall_set_MovieSceneBindingsArray'
                                (( (ULevel *) _s_self )->*(&_staticcall_set_MovieSceneBindingsArray::MovieSceneBindingsArray)) = (*(( (TArray<UObject *> *) (::unreal::helpers::UEPointer::getPointer(_s_value)) )));`
                                                       
And extern generator is not running:
`Info [2016.01.12-04.36.45:489][  0]LogCompile: Found 2 script generator plugins.
Info [2016.01.12-04.36.45:489][  0]LogCompile: Unable to determine output directory for HaxeInit. Cannot export script glue with 'Haxe Extern Generator Plugin'
Info [2016.01.12-04.36.45:489][  0]LogCompile: Script generator 'Haxe Extern Generator Plugin' not supported for target: MyProject8Editor`

**Comment by krupin-maxim** [comment]
Problem solved! I opened Modules window (Window->Developer Tools->Modules). Then found "HaxeInit" line, then clicked "Recompile".

**Comment by waneck** [comment]
The current project is now 4.11 - and we'll work to get 4.12 ready soon.
